# Generated by Django 5.1.2 on 2024-11-12 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('numero1', models.IntegerField()),
                ('numero2', models.IntegerField()),
                ('tipo', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'alelos',
            },
        ),
        migrations.CreateModel(
            name='Crossmatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_id', models.IntegerField()),
                ('donor_name', models.CharField(max_length=100)),
                ('donor_sex', models.CharField(max_length=10)),
                ('donor_birth_date', models.DateField()),
                ('donor_blood_type', models.CharField(max_length=3)),
                ('date_performed', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='paciente',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterModelTable(
            name='exame',
            table='exames',
        ),
        migrations.AlterModelTable(
            name='paciente',
            table='pacientes',
        ),
        migrations.CreateModel(
            name='CrossmatchPatientResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('patient_name', models.CharField(max_length=100)),
                ('total_compatible_alleles', models.IntegerField()),
                ('total_incompatible_alleles', models.IntegerField()),
                ('crossmatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_results', to='backend.crossmatch')),
            ],
        ),
        migrations.CreateModel(
            name='CrossmatchAlleleResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allele_name', models.CharField(max_length=10)),
                ('allele_value', models.FloatField()),
                ('compatibility', models.BooleanField()),
                ('patient_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allele_results', to='backend.crossmatchpatientresult')),
            ],
        ),
        migrations.CreateModel(
            name='ExameAlelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('alelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alelos', to='backend.alelo')),
                ('exame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exames_alelos', to='backend.exame')),
            ],
            options={
                'db_table': 'exames_alelos',
            },
        ),
    ]
