# Generated by Django 5.1.2 on 2024-11-12 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alelo_crossmatch_alter_paciente_id_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='crossmatch',
            table='crossmatch',
        ),
        migrations.AlterModelTable(
            name='crossmatchalleleresult',
            table='crossmatchalleleresult',
        ),
        migrations.AlterModelTable(
            name='crossmatchpatientresult',
            table='crossmatchpatientresult',
        ),
    ]
